<a href="https://colab.research.google.com/github/avikgoyal/Assignments_Python/blob/main/assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

. L is a list defined as L= [11, 12, 13, 14].
(i) WAP to add 50 and 60 to L.

In [ ]:
L=[11,12,13,14]
L.append(50)
L.append(60)
print("final list =",L)
del L[0]
print(" after deletion, list =",L)
del L[1]
print("after deletion, list =",L)
L.sort()
print("ascending list =",L)
L.sort(reverse=True)
print(" descending list =",L)
print("list is",13 in L)
if (13 in L)==True:
  print("present")
else:
  print("not present")

print(" length is",len(L))
print("sum is ",sum(L))
def oddoreven(n):
 if(n%2==0):
  return 0
 else: 
  return 1
summ=0
for n in L:
  if (oddoreven(n)==0):
    
    summ=summ+n
print(summ)

def prime(x):

  for i in range(2,x//2+1):
    if x%i == 0:
      return 0
    else:
      return 1
summm=0
for x in L:
  if (prime(x)==0):
    
    summm=summm+n
print(summm)
L.clear()
del L

final list = [11, 12, 13, 14, 50, 60]
 after deletion, list = [12, 13, 14, 50, 60]
after deletion, list = [12, 14, 50, 60]
ascending list = [12, 14, 50, 60]
 descending list = [60, 50, 14, 12]
list is False
not present
 length is 4
sum is  136
136
48

D is a dictionary defined as D= {1:5.6, 2:7.8, 3:6.6, 4:8.7, 5:7.7}.

(i) WAP to add new entry in D; key=8 and value is 8.8

(ii) WAP to remove key=2.

(iii) WAP to check weather 6 key is present in D.

(iv) WAP to count the number of elements present in D.

(v) WAP to add all the values present D.

(vi) WAP to update the value of 3 to 7.1.

(vii) WAP to clear the dictionary.

In [ ]:
D= {1:5.6, 2:7.8, 3:6.6, 4:8.7, 5:7.7}
D[8] = 8.8
print(D)
del D[2]
print(D)
print(6 in D) 
print(len(D))
print(sum(D))
D[3]=7.1
print(D)
D.clear()

{1: 5.6, 2: 7.8, 3: 6.6, 4: 8.7, 5: 7.7, 8: 8.8}
{1: 5.6, 3: 6.6, 4: 8.7, 5: 7.7, 8: 8.8}
False
5
21
{1: 5.6, 3: 7.1, 4: 8.7, 5: 7.7, 8: 8.8}

Q3. S1 is a set defined as S1= [10, 20, 30, 40, 50, 60].

 S2 is a set defined as S2= [40, 50, 60, 70, 80, 90].

(i) WAP to add 55 and 66 in Set S1.

(ii) WAP to remove 10 and 30 from Set S1.

(iii) WAP to check whether 40 is present in S1.

(iv) WAP to find the union between S1 and S2.

(v) WAP to find the intersection between S1 and S2.

(vi) WAP to find the S1 - S2.

In [ ]:
S1= set([10, 20, 30, 40, 50, 60])
S2= set([40, 50, 60, 70, 80, 90])
S1.add(55)
S1.add(30)
print(S1)
S1.remove(10)
S1.remove(40)
print(S1)
print(40 in S1)
print(S1.union(S2))
print(S1.intersection(S2))
print(S1-S2)

{40, 10, 50, 20, 55, 60, 30}
{50, 20, 55, 60, 30}
False
{70, 40, 80, 50, 20, 55, 90, 60, 30}
{50, 60}
{20, 30, 55}

Q4. Write the following program.

(i) WAP to print 100 random strings whose length between 6 and 8.

(ii) WAP to print all prime numbers between 600 and 800.

(iii) WAP to print all numbers between 100 and 1000 that are divisible by 7 and 9.

In [ ]:
import string as s
import random as r

def IsPrime(n):
  for d in range(2, n//2 + 1):
    if (n%d==0) :
      return(0)
  
  print(n)

def divisibleby(t):	
  if(t%7==0 and t%9==0):
    print(t)

	
for i in range(1,101):
  x=r.randint(6,8)
  print(x)
  y=r.sample(s.ascii_letters,x)
  string1="".join(y)
  print(string1)
 
for a in range(600,801):
  IsPrime(a)
print("doneeeeeeeeeee")
for w in range(100,1001):
  divisibleby(w)

7
soSNpTx
8
qsMcQhFv
8
ZMehRSod
6
Swbspi
8
BxjvWieV
8
TnIVlwSb
6
QyvTeD
8
zwtsIpOR
7
apwPbMm
7
nALVepD
8
ljpVNoqT
8
dHqlTOCD
8
aKfOqWHm
6
tCDKrv
8
gSWiPODY
6
IahBKD
6
kOPZQn
7
VFfsvQd
8
AQUBDzOx
6
QFNWYS
6
FLnOqy
6
WRPmZn
8
ekVqScmf
8
PkNgViaJ
6
PhETam
8
uFHmInUr
6
vyPGEZ
7
OAYPicq
7
UPmOoQG
6
DNVUEh
8
auUNAonv
7
rBeGtRM
7
ZAXGQKa
8
LhvEoxGq
6
xqKhIX
6
joyGYQ
6
zNDAbi
8
TScREyHO
7
IFJKMCA
7
eckqRPN
7
oYSzvRe
6
sfQeXd
7
kXthAwv
7
wEMyvOj
6
cmMsSD
6
JEiydY
7
PKhMund
8
ObYuQzTp
7
gatbcPM
6
grnctu
6
VUZkTg
6
kopVnL
7
JQmEhdB
6
UCkrgN
8
HELYQxnF
6
sIEGbB
7
tQoZrdp
8
oBWRnGVa
8
VtvhPTZX
7
hyduozm
7
MCbzfrF
6
RronDP
8
WPFIdqye
8
EPGNMRxC
6
skFHqO
7
TFhinxI
6
pUgHcs
6
QsKLGe
8
nfHjciDr
6
FYWZVd
7
BEtHMxz
7
uVkhlDM
6
ZRIuJP
8
PsprGTBX
8
QdARilsL
8
xXIVvAow
8
nJSdybvE
8
QEAPquyK
6
SNnXbP
8
MOVAdDxG
7
UkBfFKC
8
COxDjwaY
8
vDqRLpMQ
6
ludynt
7
XqmJTPG
8
JOvBaFGj
6
Wvqrjg
6
DcHwlJ
7
kwePlKO
8
UnxQBKot
8
gQMzAOjf
6
DeQmTM
8
AZSzmUQe
6
KDFtqp
6
oIyEgO
8
slfqbmiA
6
ABEJjL
6
HgJBPd
8
iAakTWld
8
HGfKdCBS
601
607
613
617
619
631
641
643
647
653
659
661
673
677
683
691
701
709
719
727
733
739
743
751
757
761
769
773
787
797
doneeeeeeeeeee
126
189
252
315
378
441
504
567
630
693
756
819
882
945

 WAP to create two lists of 10 random numbers between 10 and 30; Find 
(i) Common numbers in the two lists
(ii) Unique numbers in both the list
(iii) Minimum in both the list
(iv) Maximum in both the list
(v) Sum of both the list

In [ ]:
import random as r
L1=[]
L2=[]
for i in range(1,11):
  x=r.randint(10,30)
  y=r.randint(10,30)
  L1.append(x)
  L2.append(y)
print(L1,L2)

for d in range(1,10):
  for f in range(1,10):
    if(L1[d]==L2[f]):
      print(L1[d])
print("doneeeeeeeeeeeeeeeee")
f=0
for g in range(1,10):
  for h in range(1,10):
    if(L1[g]!=L2[h]):
      continue
  print(L1[g])
print(min(min(L1),min(L2)))   
print(max(max(L1),max(L2)))  
print(sum(L1)+sum(L2))

[13, 25, 28, 15, 29, 19, 12, 30, 29, 22] [13, 29, 14, 24, 16, 27, 12, 24, 30, 17]
29
12
30
29
doneeeeeeeeeeeeeeeee
25
28
15
29
19
12
30
29
22
12
30
428

WAP to create a list of 100 random numbers between 100 and 900. Count and print the: 
(i) All odd numbers
(ii) All even numbers
(iii) All prime numbers

In [ ]:
import random as r

def IsPrime(n):
  for d in range(2, n//2 + 1):
    if (n%d==0) :
      return(0)
  print(n)

     

 
     
L=[]
for i in range(1,101):
  x=r.randint(100,900)
  print(x)
  L.append(x)
  
for a in range(1,100):
  if(L[a]%2==0):
    print("even", L[a])
for g in range(1,100):
  if(L[g]%2!=0):
    print("odd", L[g])
for h in range(100):
  IsPrime(L[h])

459
898
855
596
404
373
165
401
291
712
585
821
715
661
784
808
886
504
658
887
322
272
150
500
744
872
821
556
468
288
591
143
770
767
806
626
260
429
587
627
205
863
898
700
357
593
337
384
621
880
891
451
274
276
677
562
860
844
876
634
485
335
880
412
313
855
399
857
114
730
337
579
461
508
621
222
190
421
200
315
842
400
468
409
616
517
830
504
872
803
653
896
511
235
260
857
774
479
484
514
even 898
even 596
even 404
even 712
even 784
even 808
even 886
even 504
even 658
even 322
even 272
even 150
even 500
even 744
even 872
even 556
even 468
even 288
even 770
even 806
even 626
even 260
even 898
even 700
even 384
even 880
even 274
even 276
even 562
even 860
even 844
even 876
even 634
even 880
even 412
even 114
even 730
even 508
even 222
even 190
even 200
even 842
even 400
even 468
even 616
even 830
even 504
even 872
even 896
even 260
even 774
even 484
even 514
odd 855
odd 373
odd 165
odd 401
odd 291
odd 585
odd 821
odd 715
odd 661
odd 887
odd 821
odd 591
odd 143
odd 767
odd 429
odd 587
odd 627
odd 205
odd 863
odd 357
odd 593
odd 337
odd 621
odd 891
odd 451
odd 677
odd 485
odd 335
odd 313
odd 855
odd 399
odd 857
odd 337
odd 579
odd 461
odd 621
odd 421
odd 315
odd 409
odd 517
odd 803
odd 653
odd 511
odd 235
odd 857
odd 479
373
401
821
661
887
821
587
863
593
337
677
313
857
337
461
421
409
653
857
479

D is a dictionary defined as D={1:"One",2:"Two",3:"Three",4:"Four", 5:"Five"}. 
 WAP to read all the keys and values from dictionary and write to the file in the given below format.
Key1, Value1
Key2, Value2
Key3, Value3

In [ ]:
D={1:"One",2:"Two",3:"Three",4:"Four", 5:"Five"}
f=open('file.txt','w')
for i in range(1,5):
  f.write(str(str(i)+" "+str(D[i])))
f.close()

 L is a list defined as L={"One","Two","Three","Four","Five"}.
 WAP to count the length of reach element from a list and write to the file in the given below format:
One, 3
Two, 3
Four, 4

In [ ]:
ff=open('fil2.txt','w')
L={"One","Two","Three", "Four","Five"}
for i in L:
   ff.write(str(i)+" "+str(len(i)))
  
ff.close()

 Write to the file 100 random strings whose length between 10 and 15

In [ ]:
import random as r
import random as s
f3=open('fi3.txt','w');

for i in range(100):
  l=r.randint(10,15)
  st="".join(r.sample(s.ascii_letters,l))
  f3.write(st)